-- BisWatcher: in-game watchlist for BiS item links in chat.
-- Tracks one MS list + any number of OS lists. When a watched item is
-- linked, pops a Roll MS / Roll OS / Pass prompt with configurable commands.
--
-- Import a watchlist string generated by the WotLK BiS Tracker web tool:
--   /biswatch import ms <string>
--   /biswatch import os <string>           (appends a new OS list)

local ADDON = "BisWatcher"
local FORMAT_VERSION = "BISWATCH1"

-- SavedVariables shape:
--   BisWatcherDB = {
--     enabled = true,
--     rolls = { ms = "/roll", os = "/roll 99" },
--     ms    = { header = {...}, items = { [id] = {rank, slot, sr} } } | nil
--     os    = { { header = {...}, items = {...} }, ... }
--   }

local RANK_LABEL = { top = "BiS", alt = "Alt", opt = "Optional" }
local RANK_COLOR = { top = "|cffff8000", alt = "|cffa335ee", opt = "|cff0070dd" }
local POPUP_TIMEOUT = 30   -- seconds before auto-pass

local function msg(text)
    DEFAULT_CHAT_FRAME:AddMessage("|cff9482c5[BisWatcher]|r " .. text)
end

local function ensureDB()
    if not BisWatcherDB then BisWatcherDB = {} end
    if BisWatcherDB.enabled == nil then BisWatcherDB.enabled = true end
    BisWatcherDB.rolls = BisWatcherDB.rolls or {}
    BisWatcherDB.rolls.ms = BisWatcherDB.rolls.ms or "/roll"
    BisWatcherDB.rolls.os = BisWatcherDB.rolls.os or "/roll 99"
    BisWatcherDB.os = BisWatcherDB.os or {}
end

local function countItems(list)
    if not list or not list.items then return 0 end
    local n = 0
    for _ in pairs(list.items) do n = n + 1 end
    return n
end

-- ---------------------------------------------------------------- import ----

local function split(s, sep)
    local out = {}
    for token in string.gmatch(s, "([^" .. sep .. "]+)") do table.insert(out, token) end
    return out
end

local function parseImport(str)
    if not str or str == "" then return nil, "empty string" end
    str = string.gsub(str, "^%s+", ""):gsub("%s+$", "")
    local header_part, items_part = string.match(str, "^([^~]+~[^~]+~[^~]+~[^~]+~[^~]+)~(.+)$")
    if not header_part then return nil, "malformed (no header)" end
    local h = split(header_part, "~")
    if h[1] ~= FORMAT_VERSION then
        return nil, "unsupported format version: " .. tostring(h[1])
    end
    local items = {}
    local count = 0
    for chunk in string.gmatch(items_part, "([^;]+)") do
        local fields = split(chunk, "|")
        local id = tonumber(fields[1])
        if id then
            items[id] = {
                rank = fields[2] or "opt",
                slot = fields[3] or "?",
                sr   = fields[4] == "sr",
            }
            count = count + 1
        end
    end
    return {
        header = { source = h[2], class = h[3], spec = h[4], phase = h[5] },
        items  = items,
        count  = count,
    }
end

local function describeHeader(h)
    if not h or not h.class then return "?" end
    return string.format("%s / %s / Phase %s (%s)",
        h.class, h.spec, h.phase, h.source or "?")
end

-- ----------------------------------------------------- lookup across lists ----

-- Returns array of matches: { {list_type, list_index, header, entry}, ... }
local function findMatches(itemID)
    local matches = {}
    if BisWatcherDB.ms and BisWatcherDB.ms.items and BisWatcherDB.ms.items[itemID] then
        table.insert(matches, {
            kind = "ms", index = nil,
            header = BisWatcherDB.ms.header,
            entry  = BisWatcherDB.ms.items[itemID],
        })
    end
    for i, list in ipairs(BisWatcherDB.os) do
        if list.items and list.items[itemID] then
            table.insert(matches, {
                kind = "os", index = i,
                header = list.header,
                entry  = list.items[itemID],
            })
        end
    end
    return matches
end

-- ------------------------------------------------------------- roll popup ----

local popup
local function createPopup()
    local f = CreateFrame("Frame", "BisWatcherRollPopup", UIParent, "BackdropTemplate")
    f:SetSize(420, 140)
    f:SetPoint("CENTER", 0, 100)
    f:SetFrameStrata("DIALOG")
    f:SetMovable(true); f:EnableMouse(true); f:RegisterForDrag("LeftButton")
    f:SetScript("OnDragStart", f.StartMoving)
    f:SetScript("OnDragStop", f.StopMovingOrSizing)
    -- THEME-HOOK: backdrop + button visuals live here. See TODO.md.
    -- When themable styling lands, factor this block into a Skin module
    -- selectable via BisWatcherDB.theme = "classic"|"elvui"|"minimal".
    if f.SetBackdrop then
        f:SetBackdrop({
            bgFile = "Interface/DialogFrame/UI-DialogBox-Background",
            edgeFile = "Interface/DialogFrame/UI-DialogBox-Border",
            edgeSize = 16, insets = { left = 4, right = 4, top = 4, bottom = 4 },
        })
    end

    f.title = f:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    f.title:SetPoint("TOP", 0, -12)
    f.title:SetText("|cff9482c5BisWatcher|r — Roll?")

    f.itemLine = f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    f.itemLine:SetPoint("TOP", 0, -36)
    f.itemLine:SetWidth(380); f.itemLine:SetJustifyH("CENTER")

    f.specLine = f:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    f.specLine:SetPoint("TOP", 0, -58)
    f.specLine:SetWidth(380); f.specLine:SetJustifyH("CENTER")

    local function makeBtn(label, anchor, x)
        local b = CreateFrame("Button", nil, f, "UIPanelButtonTemplate")
        b:SetSize(110, 28); b:SetText(label)
        b:SetPoint("BOTTOM", f, anchor, x, 14)
        return b
    end
    f.msBtn   = makeBtn("Roll MS",  "BOTTOM", -130)
    f.osBtn   = makeBtn("Roll OS",  "BOTTOM",    0)
    f.passBtn = makeBtn("Pass",     "BOTTOM",  130)

    f.msBtn:SetScript("OnClick", function()
        ChatFrame_SendTell(nil) -- noop, just ensures focus
        local cmd = BisWatcherDB.rolls.ms or "/roll"
        ChatFrame_OpenChat(cmd)
        ChatEdit_SendText(ChatFrame_GetEditBox(DEFAULT_CHAT_FRAME), 1)
        f:Hide()
    end)
    f.osBtn:SetScript("OnClick", function()
        local cmd = BisWatcherDB.rolls.os or "/roll 99"
        ChatFrame_OpenChat(cmd)
        ChatEdit_SendText(ChatFrame_GetEditBox(DEFAULT_CHAT_FRAME), 1)
        f:Hide()
    end)
    f.passBtn:SetScript("OnClick", function() f:Hide() end)

    f:SetScript("OnHide", function(self)
        self.activeItemID = nil
        if self.timer then self.timer:Cancel(); self.timer = nil end
    end)

    f:Hide()
    return f
end

-- Execute a slash-command string (e.g. "/roll" or "/roll 99")
local function runSlash(cmd)
    if not cmd or cmd == "" then return end
    -- Use the chat frame's edit box to invoke a slash command reliably
    local edit = ChatEdit_ChooseBoxForSend(DEFAULT_CHAT_FRAME)
    if not edit then return end
    edit:SetText(cmd)
    ChatEdit_SendText(edit, 1)
end

local function showPopup(itemID, matches)
    if not popup then popup = createPopup() end
    -- Re-bind buttons to use runSlash so it actually fires roll
    popup.msBtn:SetScript("OnClick", function()
        runSlash(BisWatcherDB.rolls.ms or "/roll")
        popup:Hide()
    end)
    popup.osBtn:SetScript("OnClick", function()
        runSlash(BisWatcherDB.rolls.os or "/roll 99")
        popup:Hide()
    end)
    popup.passBtn:SetScript("OnClick", function() popup:Hide() end)

    local _, link = GetItemInfo(itemID)
    link = link or ("item:" .. itemID)

    -- Build spec/coverage line: aggregate ms + which OS indexes
    local hasMS, osIdxs, slotInfo = false, {}, {}
    for _, m in ipairs(matches) do
        local rank = m.entry.rank
        local rankColor = RANK_COLOR[rank] or "|cffffffff"
        local rankLabel = RANK_LABEL[rank] or rank
        local label
        if m.kind == "ms" then
            hasMS = true
            label = "MS"
        else
            table.insert(osIdxs, m.index)
            label = "OS" .. m.index
        end
        local sr = m.entry.sr and " [SR]" or ""
        table.insert(slotInfo, string.format("%s: %s%s|r %s%s", label, rankColor, rankLabel, m.entry.slot, sr))
    end

    popup.itemLine:SetText(link)
    popup.specLine:SetText(table.concat(slotInfo, "   "))

    -- Disable buttons that don't apply
    if hasMS then popup.msBtn:Enable() else popup.msBtn:Disable() end
    if #osIdxs > 0 then popup.osBtn:Enable() else popup.osBtn:Disable() end

    popup.activeItemID = itemID
    popup:Show()

    -- Auto-pass timeout
    if popup.timer then popup.timer:Cancel(); popup.timer = nil end
    if C_Timer and C_Timer.NewTimer then
        popup.timer = C_Timer.NewTimer(POPUP_TIMEOUT, function()
            if popup and popup:IsShown() then popup:Hide() end
        end)
    end
end

-- ----------------------------------------------------------- chat scanning ----

local watchedChannels = {
    CHAT_MSG_LOOT = true,
    CHAT_MSG_RAID = true,
    CHAT_MSG_RAID_LEADER = true,
    CHAT_MSG_RAID_WARNING = true,
    CHAT_MSG_PARTY = true,
    CHAT_MSG_PARTY_LEADER = true,
    CHAT_MSG_GUILD = true,
    CHAT_MSG_OFFICER = true,
    CHAT_MSG_SAY = true,
    CHAT_MSG_YELL = true,
    CHAT_MSG_WHISPER = true,
}

-- Debounce: same itemID won't re-prompt within DEBOUNCE_SECONDS
local lastSeen = {}
local DEBOUNCE_SECONDS = 8

local function onItemLinkSeen(itemID)
    if not BisWatcherDB.enabled then return end
    local matches = findMatches(itemID)
    if #matches == 0 then return end
    local now = GetTime and GetTime() or 0
    if lastSeen[itemID] and (now - lastSeen[itemID]) < DEBOUNCE_SECONDS then return end
    lastSeen[itemID] = now
    showPopup(itemID, matches)
end

local function scanMessage(text)
    if not text then return end
    for itemID in string.gmatch(text, "|Hitem:(%d+)") do
        local id = tonumber(itemID)
        if id then onItemLinkSeen(id) end
    end
end

-- ----------------------------------------------------------------- frame ----

local frame = CreateFrame("Frame")
frame:RegisterEvent("ADDON_LOADED")
for evt in pairs(watchedChannels) do frame:RegisterEvent(evt) end

frame:SetScript("OnEvent", function(self, event, arg1)
    if event == "ADDON_LOADED" and arg1 == ADDON then
        ensureDB()
        local ms_n = (BisWatcherDB.ms and BisWatcherDB.ms.items) and 0 or 0
        if BisWatcherDB.ms and BisWatcherDB.ms.items then
            for _ in pairs(BisWatcherDB.ms.items) do ms_n = ms_n + 1 end
        end
        msg(string.format("loaded. MS:%d items, OS lists:%d. /biswatch for commands.",
            ms_n, #BisWatcherDB.os))
        return
    end
    if watchedChannels[event] then scanMessage(arg1) end
end)

-- ----------------------------------------------------------- config window ----

local configFrame

local function refreshConfigContent() end  -- forward declare

local function createConfigWindow()
    local f = CreateFrame("Frame", "BisWatcherConfig", UIParent, "BackdropTemplate")
    f:SetSize(540, 560)
    f:SetPoint("CENTER")
    f:SetFrameStrata("DIALOG")
    f:SetMovable(true); f:EnableMouse(true); f:RegisterForDrag("LeftButton")
    f:SetScript("OnDragStart", f.StartMoving)
    f:SetScript("OnDragStop", f.StopMovingOrSizing)
    f:SetClampedToScreen(true)
    -- THEME-HOOK: same skin treatment as roll popup. See TODO.md.
    if f.SetBackdrop then
        f:SetBackdrop({
            bgFile = "Interface/DialogFrame/UI-DialogBox-Background",
            edgeFile = "Interface/DialogFrame/UI-DialogBox-Border",
            edgeSize = 16, insets = { left = 4, right = 4, top = 4, bottom = 4 },
        })
    end

    f.title = f:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    f.title:SetPoint("TOP", 0, -14)
    f.title:SetText("|cff9482c5BisWatcher|r")

    f.close = CreateFrame("Button", nil, f, "UIPanelCloseButton")
    f.close:SetPoint("TOPRIGHT", -6, -6)

    -- Enable / disable scanning
    f.enableCB = CreateFrame("CheckButton", nil, f, "UICheckButtonTemplate")
    f.enableCB:SetPoint("TOPLEFT", 18, -44)
    f.enableCB.text = f.enableCB:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    f.enableCB.text:SetPoint("LEFT", f.enableCB, "RIGHT", 2, 0)
    f.enableCB.text:SetText("Scanning enabled")
    f.enableCB:SetScript("OnClick", function(self)
        BisWatcherDB.enabled = self:GetChecked() and true or false
    end)

    -- Roll commands
    local function rollBox(parent, label, anchorY)
        local lbl = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        lbl:SetPoint("TOPLEFT", 18, anchorY)
        lbl:SetText(label)
        local box = CreateFrame("EditBox", nil, parent, "InputBoxTemplate")
        box:SetSize(180, 22); box:SetAutoFocus(false)
        box:SetPoint("LEFT", lbl, "RIGHT", 18, 0)
        return box, lbl
    end
    f.msRoll = rollBox(f, "MS roll command:", -78)
    f.osRoll = rollBox(f, "OS roll command:", -106)
    f.msRoll:SetScript("OnEnterPressed", function(self)
        BisWatcherDB.rolls.ms = self:GetText() or "/roll"
        self:ClearFocus()
        msg("MS roll: " .. BisWatcherDB.rolls.ms)
    end)
    f.osRoll:SetScript("OnEnterPressed", function(self)
        BisWatcherDB.rolls.os = self:GetText() or "/roll 99"
        self:ClearFocus()
        msg("OS roll: " .. BisWatcherDB.rolls.os)
    end)

    -- Loaded watchlists list
    local listLbl = f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    listLbl:SetPoint("TOPLEFT", 18, -142)
    listLbl:SetText("Loaded watchlists")
    f.listLbl = listLbl

    f.listContainer = CreateFrame("Frame", nil, f)
    f.listContainer:SetPoint("TOPLEFT", 18, -162)
    f.listContainer:SetSize(500, 130)
    f.listRows = {}

    -- Import paste area
    local pasteLbl = f:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    pasteLbl:SetPoint("TOPLEFT", 18, -302)
    pasteLbl:SetText("Paste import string from the web tool:")

    local scroll = CreateFrame("ScrollFrame", "BisWatcherPasteScroll", f, "UIPanelScrollFrameTemplate")
    scroll:SetPoint("TOPLEFT", 18, -322)
    scroll:SetSize(480, 110)
    if scroll.SetBackdrop then
        scroll:SetBackdrop({
            bgFile = "Interface/Tooltips/UI-Tooltip-Background",
            edgeFile = "Interface/Tooltips/UI-Tooltip-Border",
            edgeSize = 12, insets = { left = 3, right = 3, top = 3, bottom = 3 },
        })
        scroll:SetBackdropColor(0, 0, 0, 0.7)
    end

    local pasteEdit = CreateFrame("EditBox", nil, scroll)
    pasteEdit:SetMultiLine(true)
    pasteEdit:SetAutoFocus(false)
    pasteEdit:SetFontObject(ChatFontNormal)
    pasteEdit:SetSize(460, 110)
    pasteEdit:SetScript("OnEscapePressed", pasteEdit.ClearFocus)
    pasteEdit:SetMaxLetters(0)
    scroll:SetScrollChild(pasteEdit)
    f.pasteEdit = pasteEdit

    -- Status line
    f.status = f:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    f.status:SetPoint("BOTTOM", 0, 50)
    f.status:SetWidth(500); f.status:SetJustifyH("CENTER")

    -- Helper: strip leading "/biswatch import (ms|os) " if user pasted whole command
    local function stripCommandPrefix(text)
        text = string.gsub(text or "", "^%s+", ""):gsub("%s+$", "")
        local rest = string.match(text, "^/[bB][wWiI]%w*%s+import%s+%S+%s+(.+)$")
        if rest then
            local kind = string.match(text, "^/%S+%s+import%s+(%S+)")
            return rest, string.lower(kind or "")
        end
        return text, nil
    end

    -- Import buttons
    local function doImport(kindOverride)
        local raw = pasteEdit:GetText()
        local body, kindFromPaste = stripCommandPrefix(raw)
        local kind = kindOverride or kindFromPaste
        if not kind or (kind ~= "ms" and kind ~= "os") then
            f.status:SetText("|cffff5555Pick MS or OS|r")
            return
        end
        local parsed, err = parseImport(body)
        if not parsed then
            f.status:SetText("|cffff5555import failed:|r " .. (err or "?"))
            return
        end
        if kind == "ms" then
            BisWatcherDB.ms = { header = parsed.header, items = parsed.items }
            f.status:SetText(string.format("|cff1eff00MS loaded:|r %d items, %s",
                parsed.count, describeHeader(parsed.header)))
        else
            table.insert(BisWatcherDB.os, { header = parsed.header, items = parsed.items })
            f.status:SetText(string.format("|cffa335eeOS%d added:|r %d items, %s",
                #BisWatcherDB.os, parsed.count, describeHeader(parsed.header)))
        end
        pasteEdit:SetText("")
        refreshConfigContent()
    end

    local msBtn = CreateFrame("Button", nil, f, "UIPanelButtonTemplate")
    msBtn:SetSize(150, 24); msBtn:SetText("Import as MS (replace)")
    msBtn:SetPoint("BOTTOMLEFT", 24, 18)
    msBtn:SetScript("OnClick", function() doImport("ms") end)

    local osBtn = CreateFrame("Button", nil, f, "UIPanelButtonTemplate")
    osBtn:SetSize(150, 24); osBtn:SetText("Import as OS (append)")
    osBtn:SetPoint("LEFT", msBtn, "RIGHT", 10, 0)
    osBtn:SetScript("OnClick", function() doImport("os") end)

    local clearBtn = CreateFrame("Button", nil, f, "UIPanelButtonTemplate")
    clearBtn:SetSize(110, 24); clearBtn:SetText("Clear paste")
    clearBtn:SetPoint("LEFT", osBtn, "RIGHT", 10, 0)
    clearBtn:SetScript("OnClick", function()
        pasteEdit:SetText("")
        f.status:SetText("")
    end)

    f:Hide()
    return f
end

-- Render the "Loaded watchlists" list of rows
refreshConfigContent = function()
    if not configFrame then return end
    -- Sync controls from DB
    configFrame.enableCB:SetChecked(BisWatcherDB.enabled and true or false)
    configFrame.msRoll:SetText(BisWatcherDB.rolls.ms or "/roll")
    configFrame.osRoll:SetText(BisWatcherDB.rolls.os or "/roll 99")

    -- Hide old rows
    for _, row in ipairs(configFrame.listRows) do row:Hide() end

    local rows = {}
    local function addRow(idx, label, count, header, onRemove)
        local row = configFrame.listRows[idx]
        if not row then
            row = CreateFrame("Frame", nil, configFrame.listContainer)
            row:SetSize(500, 22)
            row.text = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
            row.text:SetPoint("LEFT", 4, 0); row.text:SetJustifyH("LEFT")
            row.text:SetWidth(420)
            row.btn = CreateFrame("Button", nil, row, "UIPanelButtonTemplate")
            row.btn:SetSize(60, 20); row.btn:SetText("Remove")
            row.btn:SetPoint("RIGHT", -4, 0)
            configFrame.listRows[idx] = row
        end
        row:SetPoint("TOPLEFT", configFrame.listContainer, "TOPLEFT", 0, -(idx-1)*24)
        row.text:SetText(string.format("|cffffd100%s|r  %d items   |cff888888%s|r",
            label, count, describeHeader(header)))
        row.btn:SetScript("OnClick", onRemove)
        row:Show()
        table.insert(rows, row)
    end

    local idx = 0
    if BisWatcherDB.ms and BisWatcherDB.ms.items then
        idx = idx + 1
        addRow(idx, "MS", countItems(BisWatcherDB.ms), BisWatcherDB.ms.header, function()
            BisWatcherDB.ms = nil
            msg("MS cleared.")
            refreshConfigContent()
        end)
    end
    for i, list in ipairs(BisWatcherDB.os) do
        idx = idx + 1
        local osI = i
        addRow(idx, "OS" .. osI, countItems(list), list.header, function()
            table.remove(BisWatcherDB.os, osI)
            msg("OS" .. osI .. " removed.")
            refreshConfigContent()
        end)
    end
    if idx == 0 then
        idx = 1
        addRow(idx, "(none)", 0, nil, function() end)
        configFrame.listRows[idx].btn:Hide()
    end
end

local function showConfig()
    if not configFrame then configFrame = createConfigWindow() end
    refreshConfigContent()
    configFrame:Show()
end

-- ---------------------------------------------------------- slash commands ----

SLASH_BISWATCHER1 = "/biswatch"
SLASH_BISWATCHER2 = "/bw"
SlashCmdList["BISWATCHER"] = function(input)
    input = input or ""
    local cmd, rest = string.match(input, "^(%S+)%s*(.-)$")
    cmd = cmd and string.lower(cmd) or ""

    -- No args opens the config window
    if cmd == "" or cmd == "config" or cmd == "gui" or cmd == "show" then
        showConfig()
        return
    end

    if cmd == "help" then
        msg("|cff9482c5/biswatch|r opens the config window. Slash shortcuts:")
        msg("  |cffffd100import ms <string>|r       -- replace main-spec watchlist")
        msg("  |cffffd100import os <string>|r       -- append a new OS watchlist")
        msg("  |cffffd100status|r                   -- show what's loaded + roll commands")
        msg("  |cffffd100list [ms|os <N>]|r          -- list watched items")
        msg("  |cffffd100clear [ms|os|all]|r         -- clear watchlists (default: ms)")
        msg("  |cffffd100roll ms <command>|r        -- set MS roll command (default /roll)")
        msg("  |cffffd100roll os <command>|r        -- set OS roll command (default /roll 99)")
        msg("  |cffffd100toggle|r                   -- enable/disable scanning")
        msg("  |cffffd100test <itemID>|r            -- simulate a link")
        return
    end

    if cmd == "import" then
        local kind, str = string.match(rest, "^(%S+)%s+(.+)$")
        if not kind then msg("usage: /biswatch import <ms|os> <string>"); return end
        kind = string.lower(kind)
        local parsed, err = parseImport(str)
        if not parsed then msg("|cffff5555import failed:|r " .. err); return end
        if kind == "ms" then
            BisWatcherDB.ms = { header = parsed.header, items = parsed.items }
            msg(string.format("|cff1eff00MS|r set: %d items, %s", parsed.count, describeHeader(parsed.header)))
        elseif kind == "os" then
            table.insert(BisWatcherDB.os, { header = parsed.header, items = parsed.items })
            msg(string.format("|cffa335eeOS%d|r added: %d items, %s",
                #BisWatcherDB.os, parsed.count, describeHeader(parsed.header)))
        else
            msg("usage: /biswatch import <ms|os> <string>")
        end
        return
    end

    if cmd == "status" then
        msg(string.format("scanning: %s | MS roll: |cffffd100%s|r | OS roll: |cffffd100%s|r",
            BisWatcherDB.enabled and "|cff1eff00ON|r" or "|cffff5555OFF|r",
            BisWatcherDB.rolls.ms, BisWatcherDB.rolls.os))
        if BisWatcherDB.ms and BisWatcherDB.ms.header then
            msg(string.format("MS (%d items): %s", countItems(BisWatcherDB.ms), describeHeader(BisWatcherDB.ms.header)))
        else
            msg("MS: (none)")
        end
        for i, list in ipairs(BisWatcherDB.os) do
            msg(string.format("OS%d (%d items): %s", i, countItems(list), describeHeader(list.header)))
        end
        return
    end

    if cmd == "list" then
        local kind, idx = string.match(rest, "^(%S+)%s*(%S*)$")
        kind = kind and string.lower(kind) or "ms"
        local target
        if kind == "ms" then target = BisWatcherDB.ms
        elseif kind == "os" then
            local n = tonumber(idx) or 1
            target = BisWatcherDB.os[n]
            if not target then msg("OS" .. n .. " not loaded"); return end
        else target = BisWatcherDB.ms end
        if not target or not target.items then msg("nothing loaded"); return end
        for id, e in pairs(target.items) do
            local _, link = GetItemInfo(id)
            msg(string.format("  %s%s|r %s %s%s",
                RANK_COLOR[e.rank] or "", RANK_LABEL[e.rank] or e.rank,
                link or ("item:" .. id), e.slot, e.sr and " [SR]" or ""))
        end
        return
    end

    if cmd == "clear" then
        local target = string.lower(rest or "")
        if target == "" or target == "ms" then
            BisWatcherDB.ms = nil
            msg("MS cleared.")
        elseif target == "os" then
            BisWatcherDB.os = {}
            msg("all OS lists cleared.")
        elseif target == "all" then
            BisWatcherDB.ms = nil; BisWatcherDB.os = {}
            msg("all watchlists cleared.")
        else
            msg("usage: /biswatch clear [ms|os|all]")
        end
        return
    end

    if cmd == "roll" then
        local which, val = string.match(rest, "^(%S+)%s+(.+)$")
        if not which then msg("usage: /biswatch roll <ms|os> <command>"); return end
        which = string.lower(which)
        if which == "ms" then BisWatcherDB.rolls.ms = val; msg("MS roll: " .. val)
        elseif which == "os" then BisWatcherDB.rolls.os = val; msg("OS roll: " .. val)
        else msg("usage: /biswatch roll <ms|os> <command>") end
        return
    end

    if cmd == "toggle" then
        BisWatcherDB.enabled = not BisWatcherDB.enabled
        msg("scanning: " .. (BisWatcherDB.enabled and "|cff1eff00ON|r" or "|cffff5555OFF|r"))
        return
    end

    if cmd == "test" then
        local id = tonumber(rest)
        if not id then msg("usage: /biswatch test <itemID>"); return end
        lastSeen[id] = nil  -- bypass debounce for tests
        local matches = findMatches(id)
        if #matches == 0 then msg("itemID " .. id .. " is not in any watchlist"); return end
        showPopup(id, matches)
        return
    end

    msg("unknown command. try /biswatch help")
end
